version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: |
              git config user.email "ethangk@gmail.com"
              git config user.name "Ethan Katzenberg"
            - run: npm run predeploy
            - run: npm run deploy
workflows:
    build:
      jobs:
        - build:
            filters:
              branches:
                only: content
