version: 2.0
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    branches:
      only:
        - content
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run predeploy
            - run: npm run deploy
workflows:
    build:
      jobs:
        - build
